/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      typography: () => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': 'var(--color-foreground)',
            '--tw-prose-headings': 'var(--color-foreground)',
            '--tw-prose-lead': 'var(--color-muted-foreground)',
            '--tw-prose-bold': 'var(--color-foreground)',
            '--tw-prose-counters': 'var(--color-foreground)',
            '--tw-prose-bullets': 'var(--color-foreground)',
            '--tw-prose-hr': 'var(--color-border)',
            '--tw-prose-quotes': 'var(--color-foreground)',
            '--tw-prose-quote-borders': 'var(--color-border)',
            '--tw-prose-captions': 'var(--color-secondary)',
            '--tw-prose-code': 'var(--color-foreground)',
            '--tw-prose-pre-code': 'var(--color-foreground)',
            '--tw-prose-pre-bg': 'var(--color-background)',
            '--tw-prose-th-borders': 'var(--color-border)',
            '--tw-prose-td-borders': 'var(--color-border)',
            '--tw-prose-invert-body': 'var(--color-foreground)/90',
            '--tw-prose-invert-headings': 'var(--color-foreground)',
            '--tw-prose-invert-lead': 'var(--color-foreground)',
            '--tw-prose-invert-links': 'var(--color-foreground)',
            '--tw-prose-invert-bold': 'var(--color-foreground)',
            '--tw-prose-invert-counters': 'var(--color-foreground)',
            '--tw-prose-invert-bullets': 'var(--color-foreground)',
            '--tw-prose-invert-hr': 'var(--color-border)',
            '--tw-prose-invert-quotes': 'var(--color-foreground)',
            '--tw-prose-invert-quote-borders': 'var(--color-border)',
            '--tw-prose-invert-captions': 'var(--color-foreground)',
            '--tw-prose-invert-code': 'var(--color-foreground)',
            '--tw-prose-invert-pre-code': 'var(--color-foreground)',
            '--tw-prose-invert-pre-bg': 'var(--color-background)',
            '--tw-prose-invert-th-borders': 'var(--color-border)',
            '--tw-prose-invert-td-borders': 'var(--color-border)',
          },
        },
      }),
    },
  },
}
