/* Notice: This file is generated by scripts/auto-routes.ts */

import { createElement } from 'react'
import PostWrapper from '../components/PostWrapper'
import Page_0 from '../../pages/index.mdx'
import Page_1 from '../../pages/demos/index'
import Page_2 from '../../pages/essay/farewell-my-lovely.mdx'
import Page_3 from '../../pages/essay/index'
import Page_4 from '../../pages/essay/the-cherry-orchard.mdx'
import Page_5 from '../../pages/notes/function-length.mdx'
import Page_6 from '../../pages/notes/index'
import Page_7 from '../../pages/notes/js-array-fill.mdx'
import Page_8 from '../../pages/notes/js-logical-operator.mdx'
import Page_9 from '../../pages/notes/js-string-and-regexp.mdx'
import Page_10 from '../../pages/notes/overload-in-ts.mdx'
import Page_11 from '../../pages/notes/regexp-test-undefined.mdx'
import Page_12 from '../../pages/notes/string-to-ascii.mdx'
import Page_13 from '../../pages/notes/this-in-js-prototype-function.mdx'
import Page_14 from '../../pages/notes/ts-non-null-operator.mdx'
import Page_15 from '../../pages/blog/client-session-storage.mdx'
import Page_16 from '../../pages/blog/critical-rendering-path.mdx'
import Page_17 from '../../pages/blog/csrf-and-xss.mdx'
import Page_18 from '../../pages/blog/deep-clone-in-js.mdx'
import Page_19 from '../../pages/blog/empty-object-in-ts.mdx'
import Page_20 from '../../pages/blog/how-to-win-at-cors.mdx'
import Page_21 from '../../pages/blog/import-meta-glob-and-auto-routes.mdx'
import Page_22 from '../../pages/blog/index'
import Page_23 from '../../pages/blog/js-event-loop.mdx'
import Page_24 from '../../pages/blog/promise-a-plus.mdx'
import Page_25 from '../../pages/blog/race-condition-in-vue-and-react.mdx'
import Page_26 from '../../pages/blog/ssg-in-flog.mdx'
import Page_27 from '../../pages/blog/tsconfig-notes.mdx'
import Page_28 from '../../pages/blog/vue-node-mysql-deployment.mdx'
import Page_29 from '../../pages/blog/webpack4-migration-rfc.mdx'
import Page_30 from '../../pages/projects/index'

const routes = [
  {
    caseSensitive: true,
    path: '/',
    element: createElement(PostWrapper, { path: '/' }, createElement(Page_0))
  },
  {
    caseSensitive: true,
    path: 'demos',
    children: [
      {
        caseSensitive: true,
        path: '',
        element: createElement(
          PostWrapper,
          { path: '/' },
          createElement(Page_1)
        )
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'essay',
    children: [
      {
        caseSensitive: true,
        path: 'farewell-my-lovely',
        element: createElement(
          PostWrapper,
          { path: 'farewell-my-lovely' },
          createElement(Page_2)
        )
      },
      {
        caseSensitive: true,
        path: '',
        children: [
          {
            caseSensitive: true,
            path: '',
            element: createElement(
              PostWrapper,
              { path: '/' },
              createElement(Page_3)
            )
          },
          {
            caseSensitive: true,
            path: 'the-cherry-orchard',
            element: createElement(
              PostWrapper,
              { path: 'the-cherry-orchard' },
              createElement(Page_4)
            )
          }
        ]
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'notes',
    children: [
      {
        caseSensitive: true,
        path: 'function-length',
        element: createElement(
          PostWrapper,
          { path: 'function-length' },
          createElement(Page_5)
        )
      },
      {
        caseSensitive: true,
        path: '',
        children: [
          {
            caseSensitive: true,
            path: '',
            element: createElement(
              PostWrapper,
              { path: '/' },
              createElement(Page_6)
            )
          },
          {
            caseSensitive: true,
            path: 'js-array-fill',
            element: createElement(
              PostWrapper,
              { path: 'js-array-fill' },
              createElement(Page_7)
            )
          },
          {
            caseSensitive: true,
            path: 'js-logical-operator',
            element: createElement(
              PostWrapper,
              { path: 'js-logical-operator' },
              createElement(Page_8)
            )
          },
          {
            caseSensitive: true,
            path: 'js-string-and-regexp',
            element: createElement(
              PostWrapper,
              { path: 'js-string-and-regexp' },
              createElement(Page_9)
            )
          },
          {
            caseSensitive: true,
            path: 'overload-in-ts',
            element: createElement(
              PostWrapper,
              { path: 'overload-in-ts' },
              createElement(Page_10)
            )
          },
          {
            caseSensitive: true,
            path: 'regexp-test-undefined',
            element: createElement(
              PostWrapper,
              { path: 'regexp-test-undefined' },
              createElement(Page_11)
            )
          },
          {
            caseSensitive: true,
            path: 'string-to-ascii',
            element: createElement(
              PostWrapper,
              { path: 'string-to-ascii' },
              createElement(Page_12)
            )
          },
          {
            caseSensitive: true,
            path: 'this-in-js-prototype-function',
            element: createElement(
              PostWrapper,
              { path: 'this-in-js-prototype-function' },
              createElement(Page_13)
            )
          },
          {
            caseSensitive: true,
            path: 'ts-non-null-operator',
            element: createElement(
              PostWrapper,
              { path: 'ts-non-null-operator' },
              createElement(Page_14)
            )
          }
        ]
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'blog',
    children: [
      {
        caseSensitive: true,
        path: 'client-session-storage',
        element: createElement(
          PostWrapper,
          { path: 'client-session-storage' },
          createElement(Page_15)
        )
      },
      {
        caseSensitive: true,
        path: '',
        children: [
          {
            caseSensitive: true,
            path: 'critical-rendering-path',
            element: createElement(
              PostWrapper,
              { path: 'critical-rendering-path' },
              createElement(Page_16)
            )
          },
          {
            caseSensitive: true,
            path: 'csrf-and-xss',
            element: createElement(
              PostWrapper,
              { path: 'csrf-and-xss' },
              createElement(Page_17)
            )
          },
          {
            caseSensitive: true,
            path: 'deep-clone-in-js',
            element: createElement(
              PostWrapper,
              { path: 'deep-clone-in-js' },
              createElement(Page_18)
            )
          },
          {
            caseSensitive: true,
            path: 'empty-object-in-ts',
            element: createElement(
              PostWrapper,
              { path: 'empty-object-in-ts' },
              createElement(Page_19)
            )
          },
          {
            caseSensitive: true,
            path: 'how-to-win-at-cors',
            element: createElement(
              PostWrapper,
              { path: 'how-to-win-at-cors' },
              createElement(Page_20)
            )
          },
          {
            caseSensitive: true,
            path: 'import-meta-glob-and-auto-routes',
            element: createElement(
              PostWrapper,
              { path: 'import-meta-glob-and-auto-routes' },
              createElement(Page_21)
            )
          },
          {
            caseSensitive: true,
            path: '',
            element: createElement(
              PostWrapper,
              { path: '/' },
              createElement(Page_22)
            )
          },
          {
            caseSensitive: true,
            path: 'js-event-loop',
            element: createElement(
              PostWrapper,
              { path: 'js-event-loop' },
              createElement(Page_23)
            )
          },
          {
            caseSensitive: true,
            path: 'promise-a-plus',
            element: createElement(
              PostWrapper,
              { path: 'promise-a-plus' },
              createElement(Page_24)
            )
          },
          {
            caseSensitive: true,
            path: 'race-condition-in-vue-and-react',
            element: createElement(
              PostWrapper,
              { path: 'race-condition-in-vue-and-react' },
              createElement(Page_25)
            )
          },
          {
            caseSensitive: true,
            path: 'ssg-in-flog',
            element: createElement(
              PostWrapper,
              { path: 'ssg-in-flog' },
              createElement(Page_26)
            )
          },
          {
            caseSensitive: true,
            path: 'tsconfig-notes',
            element: createElement(
              PostWrapper,
              { path: 'tsconfig-notes' },
              createElement(Page_27)
            )
          },
          {
            caseSensitive: true,
            path: 'vue-node-mysql-deployment',
            element: createElement(
              PostWrapper,
              { path: 'vue-node-mysql-deployment' },
              createElement(Page_28)
            )
          },
          {
            caseSensitive: true,
            path: 'webpack4-migration-rfc',
            element: createElement(
              PostWrapper,
              { path: 'webpack4-migration-rfc' },
              createElement(Page_29)
            )
          }
        ]
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'projects',
    children: [
      {
        caseSensitive: true,
        path: '',
        element: createElement(
          PostWrapper,
          { path: '/' },
          createElement(Page_30)
        )
      }
    ]
  }
]

export default routes
