/* Notice: This file is generated by scripts/auto-routes.ts */

import { createElement } from 'react'
import PostWrapper from '../components/PostWrapper'
const Page_0 = (await import('../../pages/index.mdx')).default
const Page_1 = (await import('../../pages/blog/client-session-storage.mdx'))
  .default
const Page_2 = (await import('../../pages/blog/critical-rendering-path.mdx'))
  .default
const Page_3 = (await import('../../pages/blog/csrf-and-xss.mdx')).default
const Page_4 = (await import('../../pages/blog/deep-clone-in-js.mdx')).default
const Page_5 = (await import('../../pages/blog/empty-object-in-ts.mdx'))
  .default
const Page_6 = (await import('../../pages/blog/how-to-win-at-cors.mdx'))
  .default
const Page_7 = (
  await import('../../pages/blog/import-meta-glob-and-auto-routes.mdx')
).default
const Page_8 = (await import('../../pages/blog/index')).default
const Page_9 = (await import('../../pages/blog/js-event-loop.mdx')).default
const Page_10 = (await import('../../pages/blog/promise-a-plus.mdx')).default
const Page_11 = (
  await import('../../pages/blog/race-condition-in-vue-and-react.mdx')
).default
const Page_12 = (await import('../../pages/blog/ssg-in-flog.mdx')).default
const Page_13 = (await import('../../pages/blog/tsconfig-notes.mdx')).default
const Page_14 = (await import('../../pages/blog/vue-node-mysql-deployment.mdx'))
  .default
const Page_15 = (await import('../../pages/blog/webpack4-migration-rfc.mdx'))
  .default
const Page_16 = (await import('../../pages/demos/index')).default
const Page_17 = (await import('../../pages/essay/farewell-my-lovely.mdx'))
  .default
const Page_18 = (await import('../../pages/essay/index')).default
const Page_19 = (await import('../../pages/essay/the-cherry-orchard.mdx'))
  .default
const Page_20 = (await import('../../pages/notes/function-length.mdx')).default
const Page_21 = (await import('../../pages/notes/index')).default
const Page_22 = (await import('../../pages/notes/js-array-fill.mdx')).default
const Page_23 = (await import('../../pages/notes/js-logical-operator.mdx'))
  .default
const Page_24 = (await import('../../pages/notes/js-string-and-regexp.mdx'))
  .default
const Page_25 = (await import('../../pages/notes/overload-in-ts.mdx')).default
const Page_26 = (await import('../../pages/notes/regexp-test-undefined.mdx'))
  .default
const Page_27 = (await import('../../pages/notes/string-to-ascii.mdx')).default
const Page_28 = (
  await import('../../pages/notes/this-in-js-prototype-function.mdx')
).default
const Page_29 = (await import('../../pages/notes/ts-non-null-operator.mdx'))
  .default
const Page_30 = (await import('../../pages/projects/index')).default

const routes = [
  {
    caseSensitive: true,
    path: '/',
    element: createElement(PostWrapper, { path: '/' }, createElement(Page_0))
  },
  {
    caseSensitive: true,
    path: 'blog',
    children: [
      {
        caseSensitive: true,
        path: 'client-session-storage',
        element: createElement(
          PostWrapper,
          { path: 'client-session-storage' },
          createElement(Page_1)
        )
      },
      {
        caseSensitive: true,
        path: '',
        children: [
          {
            caseSensitive: true,
            path: 'critical-rendering-path',
            element: createElement(
              PostWrapper,
              { path: 'critical-rendering-path' },
              createElement(Page_2)
            )
          },
          {
            caseSensitive: true,
            path: 'csrf-and-xss',
            element: createElement(
              PostWrapper,
              { path: 'csrf-and-xss' },
              createElement(Page_3)
            )
          },
          {
            caseSensitive: true,
            path: 'deep-clone-in-js',
            element: createElement(
              PostWrapper,
              { path: 'deep-clone-in-js' },
              createElement(Page_4)
            )
          },
          {
            caseSensitive: true,
            path: 'empty-object-in-ts',
            element: createElement(
              PostWrapper,
              { path: 'empty-object-in-ts' },
              createElement(Page_5)
            )
          },
          {
            caseSensitive: true,
            path: 'how-to-win-at-cors',
            element: createElement(
              PostWrapper,
              { path: 'how-to-win-at-cors' },
              createElement(Page_6)
            )
          },
          {
            caseSensitive: true,
            path: 'import-meta-glob-and-auto-routes',
            element: createElement(
              PostWrapper,
              { path: 'import-meta-glob-and-auto-routes' },
              createElement(Page_7)
            )
          },
          {
            caseSensitive: true,
            path: '',
            element: createElement(
              PostWrapper,
              { path: '/' },
              createElement(Page_8)
            )
          },
          {
            caseSensitive: true,
            path: 'js-event-loop',
            element: createElement(
              PostWrapper,
              { path: 'js-event-loop' },
              createElement(Page_9)
            )
          },
          {
            caseSensitive: true,
            path: 'promise-a-plus',
            element: createElement(
              PostWrapper,
              { path: 'promise-a-plus' },
              createElement(Page_10)
            )
          },
          {
            caseSensitive: true,
            path: 'race-condition-in-vue-and-react',
            element: createElement(
              PostWrapper,
              { path: 'race-condition-in-vue-and-react' },
              createElement(Page_11)
            )
          },
          {
            caseSensitive: true,
            path: 'ssg-in-flog',
            element: createElement(
              PostWrapper,
              { path: 'ssg-in-flog' },
              createElement(Page_12)
            )
          },
          {
            caseSensitive: true,
            path: 'tsconfig-notes',
            element: createElement(
              PostWrapper,
              { path: 'tsconfig-notes' },
              createElement(Page_13)
            )
          },
          {
            caseSensitive: true,
            path: 'vue-node-mysql-deployment',
            element: createElement(
              PostWrapper,
              { path: 'vue-node-mysql-deployment' },
              createElement(Page_14)
            )
          },
          {
            caseSensitive: true,
            path: 'webpack4-migration-rfc',
            element: createElement(
              PostWrapper,
              { path: 'webpack4-migration-rfc' },
              createElement(Page_15)
            )
          }
        ]
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'demos',
    children: [
      {
        caseSensitive: true,
        path: '',
        element: createElement(
          PostWrapper,
          { path: '/' },
          createElement(Page_16)
        )
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'essay',
    children: [
      {
        caseSensitive: true,
        path: 'farewell-my-lovely',
        element: createElement(
          PostWrapper,
          { path: 'farewell-my-lovely' },
          createElement(Page_17)
        )
      },
      {
        caseSensitive: true,
        path: '',
        children: [
          {
            caseSensitive: true,
            path: '',
            element: createElement(
              PostWrapper,
              { path: '/' },
              createElement(Page_18)
            )
          },
          {
            caseSensitive: true,
            path: 'the-cherry-orchard',
            element: createElement(
              PostWrapper,
              { path: 'the-cherry-orchard' },
              createElement(Page_19)
            )
          }
        ]
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'notes',
    children: [
      {
        caseSensitive: true,
        path: 'function-length',
        element: createElement(
          PostWrapper,
          { path: 'function-length' },
          createElement(Page_20)
        )
      },
      {
        caseSensitive: true,
        path: '',
        children: [
          {
            caseSensitive: true,
            path: '',
            element: createElement(
              PostWrapper,
              { path: '/' },
              createElement(Page_21)
            )
          },
          {
            caseSensitive: true,
            path: 'js-array-fill',
            element: createElement(
              PostWrapper,
              { path: 'js-array-fill' },
              createElement(Page_22)
            )
          },
          {
            caseSensitive: true,
            path: 'js-logical-operator',
            element: createElement(
              PostWrapper,
              { path: 'js-logical-operator' },
              createElement(Page_23)
            )
          },
          {
            caseSensitive: true,
            path: 'js-string-and-regexp',
            element: createElement(
              PostWrapper,
              { path: 'js-string-and-regexp' },
              createElement(Page_24)
            )
          },
          {
            caseSensitive: true,
            path: 'overload-in-ts',
            element: createElement(
              PostWrapper,
              { path: 'overload-in-ts' },
              createElement(Page_25)
            )
          },
          {
            caseSensitive: true,
            path: 'regexp-test-undefined',
            element: createElement(
              PostWrapper,
              { path: 'regexp-test-undefined' },
              createElement(Page_26)
            )
          },
          {
            caseSensitive: true,
            path: 'string-to-ascii',
            element: createElement(
              PostWrapper,
              { path: 'string-to-ascii' },
              createElement(Page_27)
            )
          },
          {
            caseSensitive: true,
            path: 'this-in-js-prototype-function',
            element: createElement(
              PostWrapper,
              { path: 'this-in-js-prototype-function' },
              createElement(Page_28)
            )
          },
          {
            caseSensitive: true,
            path: 'ts-non-null-operator',
            element: createElement(
              PostWrapper,
              { path: 'ts-non-null-operator' },
              createElement(Page_29)
            )
          }
        ]
      }
    ]
  },
  {
    caseSensitive: true,
    path: 'projects',
    children: [
      {
        caseSensitive: true,
        path: '',
        element: createElement(
          PostWrapper,
          { path: '/' },
          createElement(Page_30)
        )
      }
    ]
  }
]

export default routes
